### ISSUE TITLE
Capitalized kin roles cannot be assigned

### ISSUE THREAD

**Issue by pilemodus** [daelvn/yyhybot#8]
Kin roles containing capital letters do not respond to /kin-add, /kin-remove commands (regardless if capitalized or not when using the command). At the moment, they can only be added/removed using /role commands.

![2022-07-06 18_53_55-Window](https://user-images.githubusercontent.com/108818544/177593921-71231c3c-4ec1-4020-9a1e-d75f828b3e6d.png)
![2022-07-06 19_00_13-Window](https://user-images.githubusercontent.com/108818544/177593939-bdf5b283-ac14-4bbc-af91-f9bb4e0860f7.png)

**Comment by daelvn** [comment]
Fixed this by forcing all kin roles to use lowercase, therefore making it not able to create uppercase roles
